### ISSUE TITLE
Platform always goes to zero position before roll/pitch/yaw

### ISSUE THREAD

**Issue by reykjalin** [MarginallyClever/RotaryStewartPlatform2#1]
When you try to tilt the platform or move it around the roll/pitch/yaw axes it always has to go to the zero position first. Of course, when it's at the zero position or has to go through it you don't notice it, but it's kind of annoying when you're trying to move it just a little bit.

Is there a way to fix this in the code? Is it just some setting you can change or do you actually have to rewrite the whole thing?

**Comment by i-make-robots** [comment]
Huh. Does it touch the limit switches before it rolls, or does it move to Center, flat, and then roll?

If you are at roll 5 deg and move to roll 10 deg, does it go to roll zero deg in between?

Dan

**Comment by reykjalin** [comment]
It does not touch the limit switches before rolling. Just rolls to the center, flat and then roll.
And yes, this happens when I roll first to 5 deg and then to 10 deg. 
This also happens when I roll to let's say 10 deg and then try to move it up to z=3 while keeping the roll at 10 deg. It always goes to the flat position first.

If you want I can record what happens, upload it to YouTube and send you a link.

**Comment by i-make-robots** [comment]
I think I understand.  I am busy the next few hours but then I can load the
test machine and investigate.

On Tue, Nov 3, 2015 at 8:50 AM, Kristófer Reykjalín <
notifications@github.com> wrote:

> It does not touch the limit switches before rolling. Just rolls to the
> center, flat and then roll.
> And yes, this happens when I roll first to 5 deg and then to 10 deg.
> This also happens when I roll to let's say 10 deg and then try to move it
> up to z=3 while keeping the roll at 10 deg. It always goes to the flat
> position first.
> 
> If you want I can record what happens, upload it to YouTube and send you a
> link.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarginallyClever/RotaryStewartPlatform2/issues/1#issuecomment-153414117
> .

## 

Dan Royer :: Marginally Clever http://www.marginallyclevergroup.com/ ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by reykjalin** [comment]
Thank you! That would be very much appreciated :)

**Comment by i-make-robots** [comment]
I just sent in a patch.  Looks like it was pretty obvious, but I need you to confirm it's better.

**Comment by reykjalin** [comment]
Everything seems to be working great now, thank you!

**Comment by i-make-robots** [comment]
Just a follow up for my records, what was your order number OR where did you get your stewart platform?  Feel free to PM me the information.

**Comment by reykjalin** [comment]
Um...where can I send you a PM?

**Comment by i-make-robots** [comment]
dan@marginallyclever.com
